---
version: '3'
services:
  umami:
    image: ghcr.io/ftyszyx/my_umami:1.0
    ports:
      - '8030:3000'
    environment:
      DATABASE_URL: mysql://umami:umami@db:3306/umami
      DATABASE_TYPE: mysql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/api/heartbeat']
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: mysql:5.7
    ports:
      - 9008:3306
    environment:
      MYSQL_DATABASE: umami
      MYSQL_ROOT_PASSWORD: 'umami'
      MYSQL_USER: 'umami'
      MYSQL_PASSWORD: 'umami'
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  umami-db-data:
