name: Create docker images

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image to ghcr.io
        with:
          image: my_umami
          tags: ${{ inputs.version }},latest
          buildArgs: DATABASE_TYPE= mysql
          registry: ghcr.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
